---
title: "Gov 50 Final Project"
author: Christopher Shen
description: "My Final Project"
output:
  distill::distill_article:
    self_contained: false
---



## Project Thoughts

I am interested in exploring data related to income inequality and hate crimes. I wish to examine how individuals of different financial backgrounds, income and savings amounts, tax brackets, etc., contribute to the existence of hate crimes in the US. Particularly with the rise in Asian Hate crimes because of COVID-19, I believe this question is quite relevant. Is there a correlation between the two variables? I'm looking forward to diving deeper into the data.

## Proposal

Does greater income inequality lead to more hate crimes? In this study, I plan to examine the extent to which income inequality fuels hate crimes. I hypothesize that income inequality leads to division along institutional and financial resources, creating future fractures regarding political views. Such views can incite prejudices against certain groups of people, lighting the flame for hate crimes. Further, those who sit high on the socioeconomic ladder naturally look down upon those below them — this internalized hierarchical perspective can encourage harmful prejudices and kindle hate crimes. My sample is comprised of data regarding median household income, unemployment proportion, education level, and more, from all 52 states in 2016. My explanatory variable is the median household income level of each state. My outcome variables are the average hate crimes of a population of 100,00 people of each state. If I observe a greater difference of median household income in certain states that lead to more hate crimes, that would support my hypothesis. When I run my regression of the number of hate crimes, a positive, significant coefficient would indicate support for my hypothesis.
